/*

Problem 45: Triangular, pentagonal, and hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle
Tn=n(n+1)/2
1, 3, 6, 10, 15, ...
 
Pentagonal
Pn=n(3n−1)/2
1, 5, 12, 22, 35, ...
 
Hexagonal
Hn=n(2n−1)
1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

The formula to calculate the nth number from the previous one can be found in the following link:
http://oeis.org/A046180

*/

function triPentaHexa(n) {
      // a(n+1) = 18817*a(n)+1568+1358*(192*a(n)^2+32*a(n)+1)^0.5
      let nextNumber = 0;
      nextNumber = 18817*(n-1)+1568+1358* Math.pow((192*Math.pow((n-1),2)+32*(n-1)+1),0.5);
      return nextNumber;
}

triPentaHexa(40756);
